M48
; DRILL file {KiCad 9.0.6} date 2026-03-10T14:28:35-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-10T14:28:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X104.1Y-184.409
T2
X104.1Y-223.349
T3
X104.0Y-173.2
X114.0Y-225.0
X231.0Y-173.2
X231.0Y-187.2
X276.0Y-228.0
M30
